from app.services.google_calendar_service import create_calendar_event
from app.services.automation_service import trigger_workflow
from datetime import datetime, timedelta

def schedule_meeting(
    context,
    summary: str,
    description: str,
    start: str,
    end: str,
    attendees: list[str],
):
    """
    Creates a calendar meeting and then
    sends invitation emails via n8n.
    """
# Fix invalid 24:00:00 generated by the planner
    if "T24:" in end:
        date_part, time_part = end.split("T")
        next_day = (
        datetime.fromisoformat(date_part) +
        timedelta(days=1)
        ).date()

        end = f"{next_day}T00:{time_part.split(':', 2)[1]}"

    try:
        event = create_calendar_event(
        db=context.db,
        current_user=context.current_user,
        summary=summary,
        description=description,
        start=start,
        end=end,
    )
    except Exception as e:
        return {
        "error": f"Failed to create calendar event: {str(e)}"
    }

    # 2. Send email to every attendee
    email_results = []

    for email in attendees:
        result = trigger_workflow(
            workflow="send-email",
            payload={
                "to": email,
                "subject": summary,
                "body": (
                    f"You have been invited to '{summary}'.\n\n"
                    f"Start: {start}\n"
                    f"End: {end}"
                ),
            },
        )

        email_results.append(
            {
                "email": email,
                "result": result,
            }
        )

    return {
        "result": {
            "meeting_created": True,
            "calendar_event": {
                "summary": event.get("summary", summary),
                "start": start,
                "end": end,
            },
            "emails": email_results,
        }
    }