from app.tools.tool_registry import TOOLS
from app.tools.tool_context import ToolContext


def execute_tool(
    tool_name: str,
    arguments: dict,
    context: ToolContext | None = None,
):
    """
    Execute a registered tool.

    Arguments are generated by the LLM.

    Context is provided by the backend.
    """

    tool = TOOLS.get(tool_name)

    if tool is None:
        raise ValueError(
            f"Unknown tool: {tool_name}"
        )

    if arguments is None:
        arguments = {}

    # If the tool supports runtime context,
    # pass it automatically.
    if context is not None:
        return tool.execute(
            context=context,
            **arguments,
        )

    return tool.execute(
        **arguments,
    )